### This file contains HTTP requests to test the API endpoints.

### Register a new user
curl -X POST http://localhost:8000/api/auth/register \
     -d '{"email": "test@test.com", "password": "secret"}' \
     -H 'Content-Type: application/json'

### Login with the registered user
curl -X POST http://localhost:8000/api/auth/login \
     -d '{"email": "test@test.com", "password": "secret"}' \
     -H 'Content-Type: application/json' \
     -c cookies.txt \
     -v

### logout the user
curl -X GET http://localhost:8000/api/auth/logout -v

### 
curl -X GET http://localhost:8000/api/public/data -v

###
curl -X GET http://localhost:8000/api/data -v

### Get weather data with query parameters
curl -X GET http://localhost:8000/api/public/weather?lat=60.192059&lon=24.945831&date=2025-05-02&time=14:00

### fingrid wind power data
curl -X GET http://localhost:8000/api/public/windpower -v

### fingrid wind power data range
curl -X GET http://localhost:8000/api/public/windpower/range?startTime=2025-05-01T04:00:00Z&endTime=2025-05-08T06:00:00Z

### finngrid consumption data
curl -X GET http://localhost:8000/api/public/consumption -v


### finngrid consumption data range
curl -X GET http://localhost:8000/api/public/consumption/range?startTime=2025-05-01T04:00:00Z&endTime=2025-05-08T06:00:00Z