[project]
name = "development-notebooks"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "dotenv>=0.9.9",
    "ipython>=9.2.0",
    "jupyter>=1.1.1",
    "psycopg2-binary>=2.9.10",
]
