# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

RUN pip install --upgrade pip
# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

#RUN pip install --upgrade passlib
# incompatibility issues with new bcrypt (revert to old version)
RUN pip install bcrypt==3.2.0
# Copy the rest of the application code into the container
COPY . .

# Expose the port the app runs on if you want access from host
#EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
