### This file contains HTTP requests to test the API endpoints.

### Register a new user
curl -X POST http://localhost:8000/api/auth/register \
     -d '{"email": "te@test.com", "password": "et"}' \
     -H 'Content-Type: application/json'

### Login with the registered user
curl -X POST http://localhost:8000/api/auth/login \
     -d '{"email": "test@test.com", "password": "secret"}' \
     -H 'Content-Type: application/json' \
     -c cookies.txt \
     -v

### logout the user
curl -X GET http://localhost:8000/api/auth/logout -v



### Price data endpoints
### Price data 48h
curl -X GET http://localhost:8000/api/public/data -v

### Price data today
curl -X GET http://localhost:8000/api/public/data/today -v

### Price data with range
POST http://localhost:8000/api/public/price/range
Content-Type: application/json

{
  "startTime": "2024-05-01T00:00:00Z",
  "endTime": "2024-05-01T05:00:00Z"
}


### Fingrid data endpoints
### fingrid wind power prooduction data now
curl -X GET http://localhost:8000/api/public/windpower -v

### Fingrid Windpower range
POST http://localhost:8000/api/public/windpower/range
Content-Type: application/json

{
  "startTime": "2025-05-08T04:00:00Z",
  "endTime": "2025-05-08T06:00:00Z"
}

### fingrid consumption data now
curl -X GET http://localhost:8000/api/public/consumption -v

### fingrid consumption data range
POST http://localhost:8000/api/public/consumption/range
Content-Type: application/json

{
  "startTime": "2025-05-08T04:00:00Z",
  "endTime": "2025-05-08T06:00:00Z"
}

### fingrid total production data
curl -X GET http://localhost:8000/api/public/production -v

### Fingrid total production data range
POST http://localhost:8000/api/public/production/range
Content-Type: application/json

{
  "startTime": "2025-05-08T04:00:00Z",
  "endTime": "2025-05-08T06:00:00Z"
}

### Production data 
POST http://localhost:8000/api/public/consumption/range
Content-Type: application/json

{
  "startTime": "2025-05-08T04:00:00Z",
  "endTime": "2025-05-08T06:00:00Z"
}

