### This file contains HTTP requests to test the API endpoints.

### Register a new user
curl -X POST http://localhost:8000/api/auth/register \
     -d '{"email": "test@test.com", "password": "secret"}' \
     -H 'Content-Type: application/json'

### Login with the registered user
curl -X POST http://localhost:8000/api/auth/login \
     -d '{"email": "test@test.com", "password": "secret"}' \
     -H 'Content-Type: application/json' \
     -c cookies.txt \
     -v

### logout the user
curl -X GET http://localhost:8000/api/auth/logout -v



### Price data endpoints
### Price data 48h
curl -X GET http://localhost:8000/api/public/data -v

### Price data today
curl -X GET http://localhost:8000/api/data/today -v

### Price data with range
POST http://localhost:8000/api/price/range
Content-Type: application/json

{
  "startTime": "2025-05-27T22:00:00Z",
  "endTime": "2025-05-29T21:00:00Z"
}


### Fingrid data endpoints
### fingrid wind power prooduction data now
curl -X GET http://localhost:8000/api/windpower -v

### Fingrid Windpower range
POST http://localhost:8000/api/windpower/range
Content-Type: application/json

{
  "startTime": "2025-05-08T04:00:00Z",
  "endTime": "2025-05-08T06:00:00Z"
}

### fingrid consumption data now
curl -X GET http://localhost:8000/api/consumption -v

### fingrid consumption data range
POST http://localhost:8000/api/consumption/range
Content-Type: application/json

{
  "startTime": "2025-05-08T04:00:00Z",
  "endTime": "2025-05-08T06:00:00Z"
}

### fingrid total production data
curl -X GET http://localhost:8000/api/production -v

### Fingrid total production data range
POST http://localhost:8000/api/production/range
Content-Type: application/json

{
  "startTime": "2025-01-08T04:00:00Z",
  "endTime": "2025-01-08T06:00:00Z"
}

### price average data
POST http://localhost:8000/api/price/hourlyavg
Content-Type: application/json

{
  "startTime": "2025-05-01T22:00:00Z",
  "endTime": "2025-05-29T21:00:00Z"
}

### price average data
POST http://localhost:8000/api/price/weekdayavg
Content-Type: application/json

{
  "startTime": "2025-05-01T00:00:00Z",
  "endTime": "2025-05-28T23:00:00Z"
}