services:
  # Chat Engine Service (add to project services if needed)
  chat-engine:
    container_name: chat-engine
    build:
      context: .
      dockerfile: chat-engine/Dockerfile
    env_file:
      - project.env
    ports:
      - 7860:7860
    restart: always
    profiles:
      - chat-engine
    volumes:
      - ./chat-engine:/app