@startuml
title FastAPI Server, access to data

Title: Sequence Diagram for data access
Participant Client
Participant Server
Participant Database
Participant ExternalAPI
Client->Server: POST /api/data/ <identifier>
Note over Server: Check credentials on\nprotected routes
Server->Database: query if cached
Database->Server: Success/Failure [,data]
Note over Server: On success: return data\ndirectly to client\non failure: make api call
Server->ExternalAPI: api call
ExternalAPI->Server: success/failure [,data]
Server->Client: Success/Failure [,data]
Server->Database: On success: cache data
Note over Client: On success: display data

@enduml